hidden: true
order: 4
context:
  icons:
    - angle-double-down
    - angle-double-left
    - angle-double-right
    - angle-double-up
    - angle-down
    - angle-left
    - angle-right
    - angle-up
    - apple
    - archive
    - area-chart
    - arrow-circle-down
    - arrow-circle-left
    - arrow-circle-o-left
    - arrow-circle-o-right
    - arrow-circle-right
    - arrow-circle-up
    - arrow-down
    - arrow-left
    - arrow-right
    - arrow-up
    - asterisk
    - ban
    - bar-chart
    - bars
    - binoculars
    - bookmark-o
    - bookmark
    - briefcase
    - bullseye
    - calendar-check-o
    - calendar-minus-o
    - calendar-o
    - calendar-plus-o
    - calendar-times-o
    - calendar
    - camera-retro
    - caret-down
    - caret-left
    - caret-lower-right
    - caret-right
    - caret-square-o-left
    - caret-square-o-right
    - caret-up
    - certificate
    - check-circle-o
    - check-circle
    - check-square-o
    - check-square
    - check
    - chevron-circle-down
    - chevron-circle-left
    - chevron-circle-right
    - chevron-circle-up
    - chevron-down
    - chevron-left
    - chevron-right
    - chevron-up
    - chrome
    - circle-o-notch
    - circle-o
    - circle-thin
    - circle
    - clock-o
    - clone
    - close
    - cloud-download
    - code
    - cog
    - copy
    - cut
    - database
    - desktop
    - dot-circle-o
    - download
    - dropbox
    - edit
    - ellipsis-h
    - ellipsis-v
    - envelope-o
    - envelope-square
    - envelope
    - exclamation-circle
    - exclamation-triangle
    - exclamation
    - external-link-square
    - facebook-official
    - facebook-square
    - feed
    - file-o
    - file-text-o
    - file-text
    - file
    - firefox
    - floppy-o
    - folder-o
    - folder-open-o
    - folder-open
    - folder
    - git-square
    - git
    - github-square
    - group
    - hand-grab-o
    - hand-o-down
    - hand-o-left
    - hand-o-right
    - hand-o-up
    - hand-paper-o
    - hand-scissors-o
    - heart-o
    - heart
    - history
    - info-circle
    - info
    - internet-explorer
    - keyboard-o
    - laptop
    - lightbulb-o
    - line-chart
    - linkedin-square
    - linkedin
    - linux
    - lock
    - long-arrow-down
    - long-arrow-left
    - long-arrow-right
    - long-arrow-up
    - medicine-bottle
    - medkit
    - minus-circle
    - minus-square-o
    - minus-square
    - minus
    - mobile
    - newspaper-o
    - paperclip
    - paragraph
    - pencil-square
    - pencil
    - phone-square
    - phone
    - pie-chart
    - plus-circle
    - plus-square-o
    - plus-square
    - plus
    - popout
    - print
    - question-circle
    - question
    - quote-left
    - quote-right
    - refresh
    - repeat
    - retweet
    - rotate-left
    - rss-square
    - safari
    - search
    - shopping-cart
    - slack
    - sort-asc
    - sort-desc
    - sort
    - spinner
    - square-o
    - square
    - star-half-empty
    - star-half
    - star-o
    - star
    - sticky-note-o
    - sticky-note
    - stop
    - table
    - tablet
    - tag
    - tags
    - television
    - th-large
    - th-list
    - th
    - thumb-tack
    - thumbs-down
    - thumbs-o-down
    - thumbs-o-up
    - thumbs-up
    - times-circle-o
    - times-circle
    - toggle-off
    - toggle-on
    - trash-o
    - trash
    - trello
    - twitter-square
    - twitter
    - unlock
    - user
    - whatsapp
    - windows
    - wordpress
